//! Generates `books.rs` from `data/books.toml` so the parser carries the book
//! table as static data with no runtime parsing (important for the wasm build).

use serde::Deserialize;
use std::path::PathBuf;
use std::{env, fs};
use unicode_normalization::UnicodeNormalization;

#[derive(Deserialize)]
struct Book {
    code: String,
    order: u32,
    testament: String,
    chapters: u32,
    slug: String,
    slugs: Vec<String>,
    name_en: String,
    abbr_en: Vec<String>,
    name_ta: String,
    alias_ta: Vec<String>,
    abbr_ta: Vec<String>,
}

#[derive(Deserialize)]
struct File {
    book: Vec<Book>,
}

/// Same normalisation the parser applies to input: NFC, lowercase, no spaces,
/// no dots, Tamil digits to ASCII.
fn key(s: &str) -> String {
    s.nfc()
        .flat_map(|c| c.to_lowercase())
        .filter(|c| !c.is_whitespace() && *c != '.' && *c != '-')
        .map(|c| match c {
            '\u{0BE6}'..='\u{0BEF}' => char::from_u32('0' as u32 + (c as u32 - 0x0BE6)).unwrap(),
            c => c,
        })
        .collect()
}

fn q(s: &str) -> String {
    format!("{s:?}")
}

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let toml_path = manifest_dir.join("../../data/books.toml");
    println!("cargo:rerun-if-changed={}", toml_path.display());
    let text = fs::read_to_string(&toml_path).expect("reading data/books.toml");
    let mut file: File = toml::from_str(&text).expect("parsing books.toml");
    file.book.sort_by_key(|b| b.order);
    assert_eq!(file.book.len(), 66);

    let mut out = String::new();
    out.push_str("// Generated by build.rs from data/books.toml. Do not edit.\n\n");
    out.push_str("pub static BOOKS: [Book; 66] = [\n");
    for b in &file.book {
        let names: Vec<String> = [b.name_en.clone(), b.name_ta.clone()]
            .into_iter()
            .chain(b.alias_ta.iter().cloned())
            .collect();
        out.push_str(&format!(
            "    Book {{ code: {}, order: {}, testament: {}, chapters: {}, slug: {}, name_en: {}, name_ta: {}, names: &[{}], abbr_en: &[{}], abbr_ta: &[{}] }},\n",
            q(&b.code),
            b.order,
            q(&b.testament),
            b.chapters,
            q(&b.slug),
            q(&b.name_en),
            q(&b.name_ta),
            names.iter().map(|s| q(s)).collect::<Vec<_>>().join(", "),
            b.abbr_en.iter().map(|s| q(s)).collect::<Vec<_>>().join(", "),
            b.abbr_ta.iter().map(|s| q(s)).collect::<Vec<_>>().join(", "),
        ));
    }
    out.push_str("];\n\n");

    // Exact-match lookup table: normalised variant -> book index. Sorted so the
    // runtime can binary-search. Duplicates across books are a data error.
    let mut variants: Vec<(String, usize)> = Vec::new();
    for (i, b) in file.book.iter().enumerate() {
        let mut all: Vec<&str> = vec![&b.code, &b.slug, &b.name_en, &b.name_ta];
        all.extend(b.slugs.iter().map(String::as_str));
        all.extend(b.abbr_en.iter().map(String::as_str));
        all.extend(b.alias_ta.iter().map(String::as_str));
        all.extend(b.abbr_ta.iter().map(String::as_str));
        for v in all {
            let k = key(v);
            if !k.is_empty() && !variants.iter().any(|(e, j)| *e == k && *j == i) {
                variants.push((k, i));
            }
        }
    }
    variants.sort();
    for w in variants.windows(2) {
        if w[0].0 == w[1].0 {
            panic!(
                "books.toml: '{}' maps to both {} and {}",
                w[0].0, file.book[w[0].1].code, file.book[w[1].1].code
            );
        }
    }
    out.push_str(&format!(
        "pub static VARIANTS: [(&str, u8); {}] = [\n",
        variants.len()
    ));
    for (k, i) in &variants {
        out.push_str(&format!("    ({}, {}),\n", q(k), i));
    }
    out.push_str("];\n");

    let dest = PathBuf::from(env::var("OUT_DIR").unwrap()).join("books.rs");
    fs::write(dest, out).unwrap();
}
