-- Search: real Tamil normaliser, ranked search function, anonymous query log,
-- common searches view. See docs/design.md section 6.

-- 1. Replace the placeholder normaliser. Generated columns are rebuilt because
--    Postgres does not recompute them when the function changes.
alter table public.verse_search drop column tsv, drop column text_norm;

-- Superseded by 20260907160000_search_collation_fix.sql; kept as applied.
create or replace function public.tamil_norm(t text)
returns text
language sql
immutable
parallel safe
as $$
  -- Generated by `cargo run -p tamil-norm --bin tamil-norm-sql`. Do not edit.
  select translate(
           regexp_replace(
             regexp_replace(lower(normalize(t, NFC)), '[^[:alnum:]\u0B80-\u0BFF]+', ' ', 'g'),
             '(?<=([\u0B85-\u0BB9a-z0-9][\u0BBE-\u0BCD]*){3,})(ினால்|ுடைய|ாலே|ிலே|க்கு|ால்|ில்|ின்|ோடு|ும்|ை)(?=\s|$)', '', 'g'),
           'ணநளழறஆஈஊஏஓஔீூேோௌா',
           'னனலலரஅஇஉஎஒஒிுெொொ')
$$;


alter table public.verse_search
  add column text_norm text generated always as (public.tamil_norm(text)) stored,
  add column tsv tsvector generated always as (
    case lang
      when 'en' then to_tsvector('english', text)
      else to_tsvector('simple', public.tamil_norm(text))
    end) stored;

create index verse_search_tsv  on public.verse_search using gin (tsv);
create index verse_search_trgm on public.verse_search using gin (text_norm extensions.gin_trgm_ops);

-- 2. Ranked search. Quoted queries: exact substring on the display text.
--    Otherwise full text (English stemmed, Tamil normalised); when that finds
--    fewer than five verses, trigram similarity on the normalised text is added
--    below them. `total` repeats the full count on every row for paging.
create or replace function public.search_verses(
  q text, versions text[], exact boolean default false, lim int default 50, off int default 0)
returns table (verse_id text, version text, text text, rank real, book_ord smallint, total bigint)
language sql
stable
parallel safe
as $$
  with p as (
    select public.tamil_norm(q) as nq, lower(normalize(q, NFC)) as lq
  ),
  fts as (
    select v.verse_id, v.version, v.text, v.book_ord,
           ts_rank_cd(v.tsv, case when v.lang = 'en'
                                   then websearch_to_tsquery('english', q)
                                   else websearch_to_tsquery('simple', p.nq) end) as rank
    from public.verse_search v, p
    where not exact
      and v.version = any(versions)
      and ((v.lang = 'en' and v.tsv @@ websearch_to_tsquery('english', q))
        or (v.lang <> 'en' and v.tsv @@ websearch_to_tsquery('simple', p.nq)))
  ),
  exact_hits as (
    select v.verse_id, v.version, v.text, v.book_ord, 1.0::real as rank
    from public.verse_search v, p
    where exact
      and v.version = any(versions)
      and position(p.lq in lower(v.text)) > 0
  ),
  fuzzy as (
    select v.verse_id, v.version, v.text, v.book_ord,
           (similarity(v.text_norm, p.nq) * 0.5)::real as rank
    from public.verse_search v, p
    where not exact
      and v.version = any(versions)
      and (select count(*) from fts) < 5
      and v.text_norm % p.nq
      and not exists (select 1 from fts f where f.verse_id = v.verse_id and f.version = v.version)
  ),
  hits as (
    select * from fts
    union all select * from exact_hits
    union all select * from fuzzy
  )
  select verse_id, version, text, rank, book_ord, count(*) over () as total
  from hits
  order by rank desc, book_ord, verse_id
  limit lim offset off;
$$;

grant execute on function public.search_verses(text, text[], boolean, int, int) to anon, authenticated;

-- 3. Anonymous search log: insert-only through a definer function, never read
--    directly by clients.
create table public.search_log (
  id          bigint generated always as identity primary key,
  query       text not null check (length(query) <= 120),
  lang        text not null check (lang in ('ta', 'en')),
  results     int  not null,
  searched_at timestamptz not null default now()
);
create index search_log_time on public.search_log (searched_at);
alter table public.search_log enable row level security;
-- No policies: nothing can read or write it through the API except log_search.

create or replace function public.log_search(q text, lang text, results int)
returns void
language sql
security definer
set search_path = public
as $$
  insert into public.search_log (query, lang, results)
  select trim(q), lang, results
  where length(trim(q)) between 2 and 120;
$$;
grant execute on function public.log_search(text, text, int) to anon, authenticated;

-- 4. Common searches: last 30 days, at least 5 distinct days of use, not blocked.
create table public.search_blocklist (query text primary key);

create materialized view public.common_searches as
  select lower(query) as query, lang,
         count(*)::int as count_30d,
         count(distinct searched_at::date)::int as days
  from public.search_log
  where searched_at > now() - interval '30 days'
    and lower(query) not in (select query from public.search_blocklist)
  group by lower(query), lang
  having count(distinct searched_at::date) >= 5
  order by count(*) desc;
create unique index common_searches_key on public.common_searches (query, lang);
grant select on public.common_searches to anon, authenticated;

-- 5. Nightly refresh at 02:30 UTC (08:00 IST).
create extension if not exists pg_cron with schema pg_catalog;
select cron.schedule('refresh-common-searches', '30 2 * * *',
  $$refresh materialized view concurrently public.common_searches$$);
