-- Search, third pass: tamil_norm returned a blank for every Tamil input when
-- called by the API role. Its regex used bracket ranges over the Tamil block;
-- ranges are collation-dependent and U+0B80 is unassigned, so under the API
-- session the range matched nothing and every Tamil character was replaced by
-- a space. The rebuilt function lists each character explicitly. Generated
-- columns are recomputed, and search_verses refuses blank normalised queries
-- (which previously scanned every row and hit the statement timeout).

-- BEGIN generated (supabase/generated/tamil_norm.sql)
create or replace function public.tamil_norm(t text)
returns text
language sql
immutable
parallel safe
as $$
  -- Generated by `cargo run -p tamil-norm --bin tamil-norm-sql`. Do not edit.
  -- Character classes list every Tamil code point explicitly: bracket
  -- ranges are collation-dependent in Postgres and broke under the API role.
  select translate(
           regexp_replace(
             regexp_replace(lower(normalize(t, NFC)), '[^[:alnum:]ஂஃஅஆஇஈஉஊஎஏஐஒஓஔகஙசஜஞடணதநனபமயரறலளழவஶஷஸஹாிீுூெேைொோௌ்ௐௗ௦௧௨௩௪௫௬௭௮௯௰௱௲௳௴௵௶௷௸௹௺]+', ' ', 'g'),
             '(?<=([அஆஇஈஉஊஎஏஐஒஓஔகஙசஜஞடணதநனபமயரறலளழவஶஷஸஹa-z0-9][ாிீுூெேைொோௌ்]*){3,})(ினால்|ுடைய|ாலே|ிலே|க்கு|ால்|ில்|ின்|ோடு|ும்|ை)(?=\s|$)', '', 'g'),
           'ணநளழறஆஈஊஏஓஔீூேோௌா',
           'னனலலரஅஇஉஎஒஒிுெொொ')
$$;
-- END generated

alter table public.verse_search drop column tsv, drop column text_norm;
alter table public.verse_search
  add column text_norm text generated always as (public.tamil_norm(text)) stored,
  add column tsv tsvector generated always as (
    case lang
      when 'en' then to_tsvector('english', text)
      else public.tamil_tsvector(text)
    end) stored;
create index verse_search_tsv  on public.verse_search using gin (tsv);
create index verse_search_trgm on public.verse_search using gin (text_norm extensions.gin_trgm_ops);

create or replace function public.search_verses(
  q text, versions text[], exact boolean default false, lim int default 50, off int default 0)
returns table (verse_id text, version text, text text, rank real, book_ord smallint, total bigint)
language sql
stable
parallel safe
as $$
  with p as (
    select trim(public.tamil_norm(q)) as nq,
           public.tamil_tsquery(q) as tq,
           websearch_to_tsquery('english', q) as eq
  ),
  fts as (
    select v.verse_id, v.version, v.text, v.book_ord,
           ts_rank_cd(v.tsv, case when v.lang = 'en' then p.eq else p.tq end) as rank
    from public.verse_search v, p
    where not exact
      and p.nq <> ''
      and v.version = any(versions)
      and ((v.lang = 'en' and v.tsv @@ p.eq)
        or (v.lang <> 'en' and v.tsv @@ p.tq))
  ),
  exact_hits as (
    select v.verse_id, v.version, v.text, v.book_ord, 1.0::real as rank
    from public.verse_search v, p
    where exact
      and p.nq <> ''
      and v.version = any(versions)
      and v.text_norm like '%' || p.nq || '%'   -- trigram-indexed prefilter
      and v.text ilike '%' || q || '%'           -- confirm on the display text
  ),
  fuzzy as (
    select v.verse_id, v.version, v.text, v.book_ord,
           (word_similarity(p.nq, v.text_norm) * 0.5)::real as rank
    from public.verse_search v, p
    where not exact
      and p.nq <> ''
      and length(p.nq) >= 3
      and v.version = any(versions)
      and (select count(*) from fts) < 5
      and p.nq <% v.text_norm
      and not exists (select 1 from fts f where f.verse_id = v.verse_id and f.version = v.version)
  ),
  hits as (
    select * from fts
    union all select * from exact_hits
    union all select * from fuzzy
  )
  select verse_id, version, text, rank, book_ord, count(*) over () as total
  from hits
  order by rank desc, book_ord, verse_id
  limit lim offset off;
$$;
